{% set name = "napari-guitils" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_guitils-{{ version }}.tar.gz
  sha256: 60e1bba02d45af39b9d43b680a8db3103eb6184c941204cb9a856efa7e6b2f52

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling
    - hatch-vcs
    - pip
    - python >=3.8
  run:
    - natsort
    - python >=3.8
    - qtpy

test:
  imports:
    - napari_guitils
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/napari-guitils
  summary: Utils to create napari guis
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/guiwitz/napari-guitils

extra:
  recipe-maintainers:
    - goanpeca
    - guiwitz
